# https://docs.travis-ci.com/user/customizing-the-build/
language: cpp

sudo: required

compiler:
  - gcc
  - clang

env:
  - GCC_VERSION="5" LLVM_VERSION="3.7"
  - GCC_VERSION="native" LLVM_VERSION="native"

matrix:
  #include:
  #  - compiler: gcc
  #  - compiler: clang
  allow_failures:
    - compiler: clang
    #- env: LLVM_VERSION=3.5

git:
  submodules: false

#branches:
#  only:
#    - master

before_install:
  - if [ "$GCC_VERSION" != "native" ]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; fi
  # https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test
  - if [ "$CXX" == "clang++" ] && [ "$LLVM_VERSION" != "native" ]; then sudo add-apt-repository --yes 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'; fi
  # http://llvm.org/apt/
  - if [ "$CXX" == "clang++" ] && [ "$LLVM_VERSION" != "native" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -; fi
  - sudo apt-get update -qq # UPDATE REPOS
  #- sudo apt-get upgrade -qq # UPGRADE SYSTEM TO LATEST PATCH LEVEL
  - sudo apt-get install -y -qq
  - if [ "$CXX" = "g++" ] && [ "$GCC_VERSION" != "native" ]; then sudo apt-get install -qq gcc-${GCC_VERSION} g++-${GCC_VERSION}; fi
  - if [ "$CXX" = "g++" ] && [ "$GCC_VERSION" != "native" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ "$CXX" == "clang++" ] && [ "$LLVM_VERSION" != "native" ]; then sudo apt-get --allow-unauthenticated -qq install clang-${LLVM_VERSION}; fi
  - if [ "$CXX" == "clang++" ] && [ "$LLVM_VERSION" != "native" ]; then export CXX="clang++-${LLVM_VERSION}" CC="clang-${LLVM_VERSION}"; fi
  - sudo mk/linux/setupBuildDeps.sh --quiet # INSTALL OUR DEPENDENCIES
  - $CXX --version
  - sudo ./.travis-before_install.sh

script:
# ALL THE BUILD COMMANDS HERE
  - mk/linux/build-mg.sh -c 4

notifications:
  irc:
    channels:
      - "irc.freenode.org#megaglest"
    skip_join: true
    use_notice: true
    on_success: change
    template:
      #- "[%{commit}: %{author}] %{message}"
      #- "%{build_url}"
      - "[%{repository}#%{branch} @%{commit}] %{author}): %{message}"
      - "Diff: %{compare_url}"
      - "Build: %{build_url}"
